
FROM python:3.9.8
#FROM --platform=linux/amd64 python:3.9.8
FROM --platform=linux/arm64 python:3.9.8

RUN pip install joblib

COPY ./model_binary/ ./model_binary/
COPY ./main.py .

RUN python -m pip install --upgrade pip

RUN pip install fastapi
RUN pip install uvicorn
RUN pip install tensorflow-macos==2.8.0
RUN pip install tensorflow-metal==0.4.0
RUN pip install tensorflow-hub==0.12.0
RUN pip install Keras==2.8.0
RUN pip install opencv-python
RUN pip install numpy


EXPOSE 8000:8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
